# Generated by Django 4.0.3 on 2022-03-10 22:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='api.genre'),
        ),
        migrations.AlterField(
            model_name='mix',
            name='tracklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=600, null=True), size=None), size=None),
        ),
    ]
