# Generated by Django 4.0.3 on 2022-03-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mix_genre_alter_mix_tracklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='tracklist',
        ),
    ]
