# Generated by Django 4.0.3 on 2022-03-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='soundcloudlink',
        ),
        migrations.RemoveField(
            model_name='mix',
            name='soundclouduser',
        ),
        migrations.AlterField(
            model_name='host',
            name='bio',
            field=models.CharField(max_length=800),
        ),
    ]
