# Generated by Django 4.0.3 on 2022-03-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mix_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='genre',
            field=models.ManyToManyField(blank=True, to='api.genre'),
        ),
    ]
