# Generated by Django 4.0.3 on 2022-03-14 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_favorites_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='tracklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=['N/A', 'N/A'], max_length=1000), size=None), default=['N/A', 'N/A'], size=None),
            preserve_default=False,
        ),
    ]
