# Generated by Django 4.0.3 on 2022-03-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mix_tracklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='tracklist',
            field=models.TextField(blank=True, default='N/A', max_length=1000),
        ),
    ]
